In [168]:
import numpy as np
import random;


In [169]:
POPULATION_SIZE = 20  # Adjusted population size
NUM_GENERATIONS = 100
CROSSOVER_PROBABILITY = 0.5
MUTATION_RATE = 0.1
rows = 20
cols = 40

In [170]:
B_array = (1/10) * np.array(
    [1, 2, 3, 4, 4, 6, 3, 7, 5, 5]
).T
print(B_array)

[0.1 0.2 0.3 0.4 0.4 0.6 0.3 0.7 0.5 0.5]


In [171]:
C_array = np.array(
    [[4.0, 1.0, 8.0, 6.0, 3.0, 2.0, 5.0, 8.0, 6.0, 7.0],
     [4.0, 1.0, 8.0, 6.0, 7.0, 9.0, 3.0, 1.0, 2.0, 3.6],
     [4.0, 1.0, 8.0, 6.0, 3.0, 2.0, 5.0, 8.0, 6.0, 7.0],
     [4.0, 1.0, 8.0, 6.0, 7.0, 9.0, 3.0, 1.0, 2.0, 3.6]]
)

In [172]:
def generatePopulation():
    random_sequence = np.random.randint(2, size=(rows, cols))
    reshaped_sequence = random_sequence.reshape(rows, 4, -1)
    int_values = np.sum(reshaped_sequence *
                    (2 ** np.arange(10)[::-1]), axis=2)*(10/1023)
    return random_sequence,int_values

In [173]:
random_sequence,int_values = generatePopulation()
print(int_values)

[[5.76735093 3.39198436 5.14173998 4.41837732]
 [8.0058651  9.81427175 6.07038123 0.93841642]
 [1.86705767 9.50146628 2.56109482 4.13489736]
 [3.96871945 9.70674487 5.38611926 9.05180841]
 [7.14565005 4.81915934 1.91593353 5.01466276]
 [9.39393939 4.57478006 7.31182796 0.14662757]
 [9.61876833 7.43890518 3.33333333 6.62756598]
 [9.82404692 2.65884653 7.86901271 6.41251222]
 [1.0459433  9.38416422 7.46823069 7.73216031]
 [0.14662757 7.45845552 8.31867058 4.93646139]
 [0.73313783 2.05278592 4.1544477  1.46627566]
 [9.13978495 4.36950147 2.41446725 9.45259042]
 [1.56402737 2.40469208 1.52492669 8.97360704]
 [2.10166178 1.80840665 9.98044966 7.57575758]
 [0.14662757 8.60215054 5.66959922 5.57184751]
 [0.24437928 7.68328446 8.0742913  2.30694037]
 [7.028348   4.03714565 2.19941349 1.81818182]
 [5.44477028 2.99120235 8.12316716 3.48973607]
 [4.86803519 1.06549365 1.17302053 3.93939394]
 [0.49853372 7.83968719 0.18572825 4.94623656]]


In [174]:
def fitness(X, C_array, B_array):
    val = 0.0
    m = len(C_array)
    for i in range(m):
        temp = 0.0
        for j in range(3):
            temp += (X[j] - C_array[j][i])**2 + B_array[i]
        val += 1.0 / temp
    val = -1*val
    return val

In [175]:
sum = 0.0
spinner = []
for x in int_values:
    ans = fitness(x, C_array, B_array)
    prev = sum
    sum += ans
    spinner.append((prev, sum))
print("sum =", sum)
print(spinner)

sum = -2.8891250529495927
[(0.0, -0.3599173542414661), (-0.3599173542414661, -0.5617240643490851), (-0.5617240643490851, -0.6395805586636711), (-0.6395805586636711, -0.7665103276140952), (-0.7665103276140952, -0.9199309593434808), (-0.9199309593434808, -1.0797541825035781), (-1.0797541825035781, -1.19225732082734), (-1.19225732082734, -1.2829804129491635), (-1.2829804129491635, -1.3566789483312554), (-1.3566789483312554, -1.4280387173515399), (-1.4280387173515399, -1.6114055202626314), (-1.6114055202626314, -1.717025488053417), (-1.717025488053417, -2.1271206722062237), (-2.1271206722062237, -2.1945429792266964), (-2.1945429792266964, -2.2707086156081195), (-2.2707086156081195, -2.344043538936015), (-2.344043538936015, -2.5118849900946207), (-2.5118849900946207, -2.67131394200493), (-2.67131394200493, -2.821504481704129), (-2.821504481704129, -2.8891250529495927)]


In [176]:
def spinnerFunnc():
    indices = []
    j = 4
    for k in range(j):
        i = 0
        randomVal = random.randint(0,100)*(sum/100)
        print(randomVal)
        for sp in spinner:
            if(sp[0]>randomVal>=sp[1]):
                indices.append(i)
                break
            i+=1
        print("i=",i)
    return indices


In [177]:
indices = spinnerFunnc()
print(indices)

-2.282408791830178
i= 15
-1.5890187791222758
i= 10
-0.40447750741294297
i= 1
-0.6644987621784063
i= 3
[15, 10, 1, 3]


In [184]:
def crossOver(indices, random_sequence):
    children = []
    cols = random_sequence.shape[1]  # Assuming cols is the length of the second dimension of random_sequence
    i = 0
    while i < len(indices):
        index1 = indices[i]
        index2 = indices[i + 1]
        print(index1, index2)
        i += 2
        crossover_point = random.randint(0, cols)  # Assuming cols is defined
        print("Crossover Point:", crossover_point)
        parent1 = random_sequence[index1]
        print(type(parent1))
        print(parent1)
        parent2 = random_sequence[index2]
        print(parent2)
        child = parent1[:crossover_point] , parent2[crossover_point:]
        children.append(child)
    return children

In [182]:
print(random_sequence[0])
print(random_sequence.shape)

[1 0 0 1 0 0 1 1 1 0 0 1 0 1 0 1 1 0 1 1 1 0 0 0 0 0 1 1 1 0 0 1 1 1 0 0 0
 1 0 0]
(20, 40)


In [185]:
children = crossOver(indices,random_sequence)

15 10
Crossover Point: 35
<class 'numpy.ndarray'>
[0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 0 0 0 1 1 1 0 1
 1 0 0]
[0 0 0 1 0 0 1 0 1 1 0 0 1 1 0 1 0 0 1 0 0 1 1 0 1 0 1 0 0 1 0 0 1 0 0 1 0
 1 1 0]
1 3
Crossover Point: 30
<class 'numpy.ndarray'>
[1 1 0 0 1 1 0 0 1 1 1 1 1 1 1 0 1 1 0 0 1 0 0 1 1 0 1 1 0 1 0 0 0 1 1 0 0
 0 0 0]
[0 1 1 0 0 1 0 1 1 0 1 1 1 1 1 0 0 0 0 1 1 0 0 0 1 0 0 1 1 1 1 1 1 0 0 1 1
 1 1 0]
